name: price-prediction
channels:
  - conda-forge
dependencies:
  - fastapi
  - requests
  - uvicorn
  - python-multipart
  - lightgbm
  - tqdm
  - gensim
  - pyvi
  - regex
  - asyncio
  - pandas
  - numpy
  - python-dotenv
  - pyforest
